version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "A first hello"

workflows:
  version: 2
  one_and_two:
    jobs:
      - build