name: Create Release Candidate

on:
  push:
    branches: [ "release/**" ]

  workflow_dispatch:

jobs:
  create_rc:
    if: github.event.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Refs
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Create Release
        id: create_release
        uses: xaprier/actions-semver@latest
        with:
          draft: false
          prerelease: true
          include-letter-v: true
          token: ${{ secrets.GITHUB_TOKEN }}