name: Create Release Candidate

on:
  create:
    branches: [ "release/**", "rc/**" ]

  workflow_dispatch:

jobs:
  create_rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Refs
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"