name: Merge Release Candidate

on:
  pull_request:
    types: [ "closed" ]
    branches: [ "main", "master" ]

  workflow_dispatch:

jobs:
  merge_rc:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Refs
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - uses: paulhatch/semantic-version@latest
        id: versioning
        with:
          bump_each_commit: true

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.versioning.outputs.version_tag }}
          body: Changelog Contents
          token: ${{ github.token }}

      - name: Show Docker Tags
        env:
          TAG_NAME: ${{ github.head_ref }}
          VERSION_TAG: ${{ steps.versioning.outputs.tag }}
        run: echo "tag $TAG_NAME will be re-tagged as $VERSION_TAG"