name: Merge Release Candidate

on:
  pull_request:
    types: [ "closed" ]
    branches: [ "main", "master" ]

  workflow_dispatch:

jobs:
  merge_rc:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Refs
      - uses: actions/checkout@v4
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Get Next Version
        uses: ietf-tools/semver-action@v1
        id: semver
        with:
          token: ${{ github.token }}
          branch: main

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          body: Changelog Contents
          token: ${{ github.token }}

      - name: Show Docker Tags
      - uses: actions/checkout@v4
        env:
          TAG_NAME: ${{ github.head_ref }}
          VERSION_TAG: ${{ steps.semver.outputs.next }}
        run: echo "tag $TAG_NAME will be re-tagged as $VERSION_TAG"