name: Merge Release Candidate

on:
  pull_request:
    types: [ "closed" ]
    branches: [ "main", "master" ]

  workflow_dispatch:

jobs:

  merge_rc:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Refs
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
