name: Merge Release Candidate

on:
  pull_request:
    types: [ "closed" ]
    branches: [ "main", "master" ]

  workflow_dispatch:

jobs:
  merge_rc:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Refs
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Increment Calender Version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: calver

      - name: Show Docker Tags
        env:
          TAG_NAME: ${{ github.head_ref }}
          VERSION: ${{ steps.version.outputs.version }}
        run: echo "tag $TAG_NAME with $VERSION"

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.version.outputs.version }}
          body: Changelog Contents
          token: ${{ github.token }}